### ISSUE TITLE
Improve domain of encodeable types

### ISSUE THREAD

**Issue by slashwarm** [slashwarm/elte-orarend#13]
```
        switch (parts[i + 7]) {
            case 'e':
                lesson.type = 'előadás';
                break;
            case 'g':
                lesson.type = 'gyakorlat';
                break;
            case 'e':
                lesson.type = 'elfoglaltság';
                break;
            case 'k':
                lesson.type = 'konzultáció';
                break;
            default:
                console.error('Lehetetlen típus');
        }
```
A jelenlegi típusok esetében ütközés van az `előadás` és az `elfoglaltság` közt. Valamint most nézem, hogy több típus is van, főleg más karokon, pl. tereptan. És ez csak a jéghegy csúcsa. Nem tudom, hogy lenne a legjobb ezeket tömöríteni, talán egy olyasmi, hogy `case 'x': 'egyéb'` vagy a default lesz az egyéb, és akkor valami random karakter megy oda tömörítve.

**Comment by slashwarm** [comment]
@UnicodeError0041 ha gondolod nézz rá.

**Comment by UnicodeError0041** [comment]
Köszönöm szépen, hogy felhívtad rá a figyelmem! Mindenképpen belenézek

**Comment by UnicodeError0041** [comment]
Amúgy van valami lista, hogy milyen óratípusok vannak összesen valahol?

**Comment by slashwarm** [comment]
Na ez nagyon jó kérdés. Talán neptunban lehet rá filterezni, de tényleg fogalmam sincs 😀. Szerintem elég ha ez a 4 alap működik jól, a maradék lehet ilyen "egyéb" jelölésű.
